### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by ivan127617** [m-expunged/guacamole-sharp#12]
Hello, I am a beginner of Asp.net. I don't know how to run this project, can you be more specific, or is there a video? Thank you very much!

**Comment by m-expunged** [comment]
You should be able to run the project locally through Visual Studio or the dotnet run command after cloning it. It'll open a Browser Window with Swagger that'll show you the available API endpoints.

Using Docker, there isn't much more to it than what's already in the README. No need to even clone the project if you are using Docker. You can just run the commands in the README.

You can also deploy it using e.g. IIS, but you'll have to figure that out for yourself, since there's a lot of use specific fiddling required there. I might write an example deploy later, no promises tho.

**Comment by ivan127617** [comment]
I really appreciate it
